### ISSUE TITLE
Installation and uninstallation of plugins

### ISSUE THREAD

**Issue by yangkuii** [k3ldar/.NetCorePluginManager#104]
On the page http://pluginmanager.website/SystemAdmin/Grid/7 I saw the list of plugins loaded in the Demo, but I can't do some operations on these plugins.
I want to know how these plugins are installed and uninstalled. Does it support hot-loading? What do I need to do to upgrade the plugin? Is there any documentation or demo about these? thank you

**Comment by k3ldar** [comment]
At present you can load the plugins either using UsePlugin method (http://pluginmanager.website/docs/Document/AspNetCore-PluginManager/PluginManagerService/) or by ensuring the plugin is located in the plugin folder, this can be configured in your appsettings.json (http://pluginmanager.website/SystemAdmin/Text/60) for an example.

Part of the problem with unloading at runtime would be how to re-register the route with MVC, not something I have looked into, but will give it some thought.  If this is a definitive request please add it to the issues list with your use case.

What operations are you trying to achieve?  

try looking at:

IPluginTypes interface (http://pluginmanager.website/docs/Document/PluginManager/IPluginTypesService/)
IPluginClassesService (http://pluginmanager.website/docs/Document/PluginManager/IPluginClassesService/)
IPluginHelperService (http://pluginmanager.website/docs/Document/PluginManager/IPluginHelperService/)

All of these allow you to query plugins for specific classes, or classes that inherit or implement interfaces, this razor page (https://github.com/k3ldar/.NetCorePluginManager/blob/master/Demo/NetCorePluginDemoWebsite/Views/Shared/_Layout.cshtml) will help show you how the demo uses plugins to obtain menu items  all provided by plugins.

Another to look at is SystemAdmin, this relies on plugins creating classes that it then displays (https://github.com/k3ldar/.NetCorePluginManager/blob/master/Plugins/SystemAdmin.Plugin/Helpers/SystemAdminHelper.cs) again, the plugin defines the functionality.

The upshot is it provides a framework, but you need to decide how this is utilised within your web app.  I have written quite a lot of documentation (a bit of a trawl to go through I agree) but worth scanning (http://pluginmanager.website/Docs/)

Or if there is anything specific let me know, but hopefully the above will give you a general idea :-)

Si

**Comment by k3ldar** [comment]
Closing, feel free to reopen it by responding
