### ISSUE TITLE
Routes and compiled views in 3.2

### ISSUE THREAD

**Issue by large** [k3ldar/.NetCorePluginManager#106]
**Describe the bug**
Upgrading from 3.0 to 3.2:

It seems like the app.UseMvc(routes => routes.MapRoute() ) does not work in 3.2 anymore since the compiled view is not loaded.

I believe M$ has changed the AppPart routine, that broke this, see examples:
https://github.com/aspnet/AspNetCore.Docs/tree/master/aspnetcore/mvc/advanced/app-parts

and docs:
https://github.com/aspnet/AspNetCore.Docs/issues/16522

**To Reproduce**
Create a plugin with compiled view load it by "UsePlugin()" it is not loaded.

Note: I have moved the Configure into the IInitialiseEvents as described.

**Expected behavior**
Expected that the plugin shall be loaded into the scope and make the controller available. It shows a 404 in the browser without any debug info at all on the routename described.

What have I missed since 3.2 upgrade?

**Comment by large** [comment]
I have invested some time to get everything back and running in 3.1.
Found this great article: http://blog.asteropesystems.com/post/application-parts-to-make-a-pluggable-web-application/

Check out the source: https://github.com/asteropesystems/Application-Parts-Sample-Solution/blob/master/MainWebApplication/Startup.cs

There seems to be something broken in NetCorePlugin for compiled views but this function works:

```
        private void ConfigureApplicationParts(ApplicationPartManager apm)
        {
            string rootPath = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
            var pluginsPath = Path.Combine(rootPath, "Plugins");


            // check for plugins path
            if (Directory.Exists(pluginsPath))
            {
                var assemblyFiles = Directory.GetFiles(pluginsPath, "*.*", SearchOption.AllDirectories);
                foreach (var assemblyFile in assemblyFiles)
                {
                    try
                    {
                        var assembly = Assembly.LoadFrom(assemblyFile);
                        if (assemblyFile.EndsWith(".Views.dll"))
                        {
                            apm.ApplicationParts.Add(new CompiledRazorAssemblyPart(assembly));
                        }
                        else
                        {
                            var manifestResourceNames = assembly.GetManifestResourceNames();


                            apm.ApplicationParts.Add(new AssemblyPart(assembly));
                        }
                    }
                    catch (Exception e) { }
                }
            }


            apm.FeatureProviders.Add(new ViewComponentFeatureProvider());
        }
```
Ref: https://github.com/asteropesystems/Application-Parts-Sample-Solution/blob/b06dc389a8bb3b03c7e75b35268e4b5758e4ada7/MainWebApplication/Startup.cs#L27-L57

With the combination with "Useplugin()" every resource and view is loaded as expected.
Probably something to implement into the framework @k3ldar :)

**Comment by k3ldar** [comment]
Cheers will check this out over the coming week :-)

**Comment by k3ldar** [comment]
Which version of core are you using for the compiled views, is it the latest 3.1 or an earlier version?

**Comment by large** [comment]
I use .Net Core 3.1 to compile everything.
On 3.0 it worked to just add the Views resource, but in 3.1 it seems to require both...

**Comment by k3ldar** [comment]
Yup, it's a bug, in Core 3.0 I was already loading application parts, unfortunately it was on an #if for core 3.0 only, this has been reversed and a new package (v3.2.1) has just been uploaded to nuget.

FWIW I am in the process of adding test cases so hopefully can find this type of fubar in the future

Thanks for reporting it

Si :-)
