### ISSUE TITLE
Upgrade to .Net Core 2.2

### ISSUE THREAD

**Issue by large** [k3ldar/.NetCorePluginManager#23]
Great work @k3ldar with the pluginmanager, saved me a lot of time using your framework ! 👍 
I wonder if you have plans to upgrade it to .Net Core 2.2?

**Comment by k3ldar** [comment]
Thank you, yes there are plans, need to finish the Account plugin which is my current focus.  If you wish to get involved you are more than welcome :-)

**Comment by k3ldar** [comment]
Completed, new version is 1.1.0
