### ISSUE TITLE
Compiled views?

### ISSUE THREAD

**Issue by large** [k3ldar/.NetCorePluginManager#24]
I have tested your plugin-manager and I'm impressed with it.

Your method is to use *.csfiles/statics as embedded resources and then extract it in the running-server for presentation. That works quite good, but have you considered also support for compiled views?

Check out this framework: https://github.com/GianfriAur/NETCore.Mvc.PluginsManager

Compiled views are added when a plugin.dll.view file exists:

> string ViewAssembypath = a.Key.Replace(".dll", ".Views.dll");
>                         if (File.Exists(ViewAssembypath))
>                         {
>                             services.AddMvc().ConfigureApplicationPartManager(apm =>
>                             {
>                                 foreach (var b in new CompiledRazorAssemblyApplicationPartFactory().GetApplicationParts(AssemblyLoadContext.Default.LoadFromAssemblyPath(ViewAssembypath)))
>                                     apm.ApplicationParts.Add(b);
>                             });
>                         }
> 

I have tested and it works.

**Comment by k3ldar** [comment]
Thanks for the sample code, it's here as a jira now, so will be tackled soon 👍

**Comment by large** [comment]
Great! 👍 

I also miss a way to set settings by programming (either in main or in plugins) instead of appsettings.json. 

The function `private void ExtractResources(in Assembly pluginAssembly, in PluginSetting pluginSetting)` does not work as expected when the assambly name and namespace isn't equal.

Example:
Created a class call "Plugin-A", namespace was "Plugin_A", files was then copied to "Plugin_A\Views\x.cshtml" instead of "Views\x.cshtml".

I suggest that `ExtractResources()` implements a "copy if newer" also; for example:
`if (File.GetLastWriteTime(SourceFileName).CompareTo(File.GetLastWriteTime(DestinationFilename)) > 0)`
That would reduce IO-handling and still have integrity on the files.

**Comment by k3ldar** [comment]
In version 1.1.0, look at implementing ISettingsProvider, this will allow you to use any storage mechanism as setting provider, but defaults to appsettings.json if not implemented.

**Comment by k3ldar** [comment]
Compiled Views completed and will be available through nuget with version 1.2.0
