### ISSUE TITLE
Make pluginmanager settings indepentent of json config

### ISSUE THREAD

**Issue by large** [k3ldar/.NetCorePluginManager#41]
**Is your feature request related to a problem? Please describe.**
PluginManagerService.Initialise(ILogger logger) will always use the appsettings.json when pluginmanager is inited. I couldn't find a way to override it.

**Describe the solution you'd like**
It should be implemented with the posibility to provide your own ILoadSettingsService<PluginSettings> that can be set by code.

**Describe alternatives you've considered**
Create own fork to implement it, but you know the framework best 👍

**Comment by k3ldar** [comment]
I see what you mean, I was thinking of changing the initialize method anyway and creating a default ILogger if one is not supplied, it would be an easy change to add that in too.
