### ISSUE TITLE
Net Core 3

### ISSUE THREAD

**Issue by k3ldar** [k3ldar/.NetCorePluginManager#92]
Add support for net core 3 release and remove support for candidate release

**Comment by large** [comment]
Hi @k3ldar , how is the NetCore 3 implementation going?
Just upgraded my project to v3 and it is nagging about IHostingEnvironment all over ;)

**Comment by k3ldar** [comment]
Hi,

You should be able to just swap that out for IWebHostingEnvironment, the problem I am faced with for this jira (and I am currently working on it) is that MetadataReferenceFeature has been obsoleted.  

I am trying to find the best approach to replace references to obsoleted classes/interfaces so as it will be future proof for Core 3.  

Si

**Comment by large** [comment]
I started todo so, but it failed because of the MetadataReferenceFeature. Went back to 2.2 and see how much change it would require.

They also limited the static routing so it required options inn addmcv() function too.

The framework works great on my smtp server frontend I am currently working on. So keep up the good work 👍🏼

**Comment by k3ldar** [comment]
The problem faced here is that within Microsoft.Extensions.DependencyModel the CompilationLibrary class implements a static ICompilationAssemblyResolver implementation which has no facility to add custom assembly resolver's (as far as I can tell).  This makes it very difficult to resolve for dynamically loaded modules, which this plugin manager sort of relied upon.  and results in an error of "Cannot find compilation library location for package" when trying to dynamically load packages.

The quick resolve at this point, and sadly it will remain until I can find a workaround for the ICompilationAssemblyResolver is to add plugins as a reference and call the PluginManagerService.UsePlugin() method to load plugins.  This has one advantage in that deploying the app will also deploy the appropriate plugin modules.  So SOLID and DRY principles can still be adhered to.

This Jira will be updated and a new one created for finding a workaround to the CompilationLibrary issue as it now works correctly with Net Core 3, using the UsePlugin() fix.
