### ISSUE TITLE
Create ICompilationAssemblyResolver class and add to existing collection

### ISSUE THREAD

**Issue by k3ldar** [k3ldar/.NetCorePluginManager#94]
Microsoft.Extensions.DependencyModel contains CompilationLibrary class which implements a static ICompilationAssemblyResolver implementation with no facility to add custom assembly resolver's (as far as I can tell). 

Attempt to find a way to add a custom ICompilationAssemblyResolver to help resolve dynamically loaded assemblies.

**Comment by large** [comment]
Hi @k3ldar! Did you ever figure out this issue?

**Comment by k3ldar** [comment]
Not as yet, just moved jobs/country so been a bit slow on computer, it will
be solved at some point though.  There is a workaround as it only affects
core 3, which is to call UsePlugin

Si

**Comment by large** [comment]
Congratz on your new job :)
Hopefully you'll find spare time to work on this great project in the near future.

Only reason for me to upgrade to 3.0 is Googles+ auth service is soon to be deprecated. And M$ have implemented it in 3.0 so I don't have to walk-the-line.

**Comment by large** [comment]
I upgraded to 3.0 yesterday and got the plugins to load using the UsePlugin function and .NetCorePluginManager 3.0.1. But pluginmanager did not implement the compiled razor views into the project like it used to. Controllers "Index()" is called, but the actually views are not found.
Is it related to the resolver?

Btw here is how I load each of the plugins in 3.0:

```
                workingDirectory += @"\\..\Plugins\";

                string[] dllDirectories = Directory.GetDirectories(workingDirectory);
                for (int i = 0; i < dllDirectories.Length; i++)
                {
                    string sDir = new DirectoryInfo(dllDirectories[i]).Name;
                    sDir += $@"\Plugin-{sDir}-Admin\";

#if DEBUG
                    sDir += @"bin\Debug\netcoreapp3.0\";
#endif
                    string[] dllFileNames = Directory.GetFiles(workingDirectory + sDir, "*.dll");

                    for(int o=0;o<dllFileNames.Length;o++)
                    {
                        System.Reflection.Assembly assemblyFile = Assembly.LoadFile(dllFileNames[o]);
                        var names = TypeHelper.GetLoadableTypes(assemblyFile);

                        foreach (var data in names)
                        {
                            var plugincheck = data.GetInterface("IPlugin");
                            if(plugincheck!=null)
                            {
                                PluginManagerService.UsePlugin(data);
                                break;
                            }
                        }
                    }
```

When checking the log I had same issues earlier: https://github.com/k3ldar/.NetCorePluginManager/issues/24 some how related?

**Comment by k3ldar** [comment]
It could be related, i have a chunk or work to do for the latest net core
3, as it changed a few of the behaviours, try referencing the plugin in the
project and use the UsePlugin method, does that make a difference?

Sadly i am working away at mo and have no access to my laptop to try stuff,
or even code in the evenings after work, hopefully it will change soon and
i can get back on track

**Comment by large** [comment]
I can confirm the ConfigureCompiledViews is missing, so that is missing in 3.0

It is a bummer that you don't have access to work at your project at the evening. I would recommend setting up either a server@home and use remote desktop or try Visual Studio online: https://visualstudio.microsoft.com/services/visual-studio-online/

I have friends that use the online editor and are happy with that...

**Comment by k3ldar** [comment]
Lol i bet it wouldn't quite be the same on my galaxy s10 ;-) i have plans
to get my laptop back from my kids though :-)

**Comment by k3ldar** [comment]
I am just re-looking at this, the reason those methods are not enabled for NetCore 3 is because MetadataReferenceFeatureProvider is now deprecated, this is an issue as I have to find another way of enabling views from plugins.

This link (https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-3.1) shows that it is possible to have compiled views still, I will do some tests just now to see what happens, but I am fairly certain I checked this before, from memory with plugin assemblies the compiled views were not being recognised, or at least the parts were not, I have to somehow find a way of dynamically compiling views on the fly, or upon extraction as resources.  This is the bit that is problematic as the static implementation of ICompilationAssemblyResolver does not appear to allow 3rd parties to take control.  I now have a computer with me and a little time so will try again with this one :-)

**Comment by large** [comment]
Is this releated to https://github.com/k3ldar/.NetCorePluginManager/issues/106 ?

**Comment by k3ldar** [comment]
No, the issue was a bug I introduced in 3.2 :-(
