### ISSUE TITLE
Dotnet.exe not closed if ConfigureServices() is called

### ISSUE THREAD

**Issue by large** [k3ldar/.NetCorePluginManager#95]
**Describe the bug**
The program does not close the dotnet.exe process after pushing CTRL+ C
Using .NET Core 2.2, on my project with ASP 2.5 (not 3.0 since it does not work atm for me).

Edit: I am using Kestrel and not IIS Express.

The console hangs forever:
![image](https://user-images.githubusercontent.com/535446/69911968-6b032300-1423-11ea-8a21-7a03ed73b063.png)

**To Reproduce**
On my solution it only happens if ConfigureServices() has been called and pluginmanager enabled.
Does not matter if I have any plugins loaded or not.

Edit: Testet your AspNetCore.PluginManager.DemoWebsite using Kestrel with same result, now using Kestrel and 3.0 framework:
![image](https://user-images.githubusercontent.com/535446/69911962-4c9d2780-1423-11ea-9b58-08f371e58d19.png)

I have read some places that they publish their solution first and run the dotnet.exe in a own controlled process. But that seems like a workaround other than a fix...

If I disable the pluginmanger, the ConfigureServices() does nothing, and exit works as expected.
> https://github.com/k3ldar/.NetCorePluginManager/blob/552796d51979421e1228120551cea8cbcaea0e82/NetCorePluginManager/PluginManagerService.cs#L227

Hopefully you can reproduce at your side...

**Expected behavior**
CTRL+C shutdown of all processes related with no questions asked :)

**Desktop (please complete the following information):**
Windows

**Comment by k3ldar** [comment]
Good spot, threadmanager was being initialised but not finalised, 2 threads were remaining active, the PluginManagerService class now has a static method for Finalise(), this should be called to ensure the plugin manager properly closes down and finalises all plugins, this will be version 3.0.1

**Comment by large** [comment]
Wow, quick update... Inspired me to update to 3.0 today :)
I tested your project and mine and it requires CTRL+C twice to actually quit. Strange behaviour.

**Comment by k3ldar** [comment]
Oddly, if you click in the console window, the title prefixes with
"selected" then it should only take 1 x ctrl+c, at least thats what i
observed
